In [1]:
import numpy as np

In [4]:
v=np.random.randint(low=1, high=101, size=(10))
print(v)

[51 64  7 10 22 15 83 32 77 38]


In [15]:
odd_v= v[v % 2 == 1]
print(odd_v)

[51  7 15 83 77]


In [17]:
backwards_v=np.flip(v,0)
print(backwards_v)

[38 77 32 83 15 22 10  7 64 51]


In [18]:
a = np.array([1, 2, 3, 4, 5])
b = a[1:4]
b[0] = 200
print(a[1])


200


In [21]:
m=np.random.randint(low=1, high=101, size=(5,5))
print(m)

[[48 34 20 44 77]
 [ 7 73 66 31 21]
 [32 78 86 15  9]
 [21 17 44 89 45]
 [77 55 51 54 58]]


In [28]:
flipped_m = np.array([row[::-1] for row in m])
print(flipped_m)

[[77 44 20 34 48]
 [21 31 66 73  7]
 [ 9 15 86 78 32]
 [45 89 44 17 21]
 [58 54 51 55 77]]


In [30]:
reversed_m = np.flipud(m)
print(flipped_m)

[[77 55 51 54 58]
 [21 17 44 89 45]
 [32 78 86 15  9]
 [ 7 73 66 31 21]
 [48 34 20 44 77]]


In [33]:
backwards_m=np.array([row[::-1] for row in flipped_m])
print(backwards_m)

[[58 54 51 55 77]
 [45 89 44 17 21]
 [ 9 15 86 78 32]
 [21 31 66 73  7]
 [77 44 20 34 48]]


In [34]:
snipped_m=np.array(m[1:-1, 1:-1])
print(snipped_m)

[[73 66 31]
 [78 86 15]
 [17 44 89]]
